FROM ghcr.io/puppeteer/puppeteer:23.11.1

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /usr/scr/app

COPY  package*.json ./
RUN npm ci


RUN apt-get update && apt-get install -y \
    chromium-browser \
    fonts-liberation \
    libatk-bridge2.0-0 \
    libcups2 \
    libnss3 \
    libxcomposite1 \
    libxrandr2 \
    xdg-utils


COPY . .
CMD ["node", "index.js"]